# Generated by Django 3.0.2 on 2020-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('nombre_Razonsocial', models.CharField(max_length=100)),
                ('nitCedula', models.IntegerField()),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('correoElectronico', models.EmailField(default='', max_length=30)),
                ('numeroTelefonico', models.CharField(default='', max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
