# Generated by Django 3.0.3 on 2020-03-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEvento', models.CharField(max_length=100)),
                ('precioEvento', models.IntegerField()),
                ('ubicacionEvento', models.TextField()),
                ('horaEvento', models.DateTimeField()),
                ('fechaEvento', models.DateField(help_text='(AA/MM/DD)')),
                ('restriccion', models.IntegerField(choices=[(1, 'Todos'), (2, 'Mayores De Edad'), (3, 'Mayores De 12 Anios'), (4, 'Mayores De 15 Anios')])),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
